repos:
  - repo: local
    hooks:
      - id: cargo-fmt-check
        name: Cargo fmt check
        entry: cargo fmt --check
        language: system
        types: [ rust ]
      - id: cargo-sqlx-prepare-check
        name: Cargo SQLx prepare check
        entry: cargo sqlx prepare --check --workspace
        language: system
        types: [rust]
