[workspace]
members = ["doseishared", "doseiserver", "doseiclient"]

[workspace.dependencies]
tokio = { version = "1.34.0", features = ["full"] }
serde_json = "1.0.108"
serde = { version = "1.0.193", features = ["derive"] }
