[workspace]
members = ["doseid"]
resolver = "2"

[workspace.package]
version = "0.0.3"
license = "AGPL-3.0"
repository = "https://github.com/doseiai/dosei"
authors = ["Dosei Team <hi@dosei.ai>"]
edition = "2021"

[workspace.dependencies]
