version: "3.9"

services:
  dosei:
    container_name: dosei
    restart: always
    build: .
    command: /bin/doseid --host 0.0.0.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/doseid:/root/.dosei/doseid/data
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - '80:8844'
    networks:
      - net
  postgres:
    extends:
      file: docker-compose.base.yml
      service: postgres
    networks:
      - net

networks:
  net:
    driver: bridge
