version: "3.9"
services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:16.1
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    command: >
      -c log_connections=on
      -c log_disconnections=on
  redis:
    container_name: redis
    restart: always
    image: redis:7.2.3
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./data/redis:/data
    ports:
      - '6379:6379'
