[package]
name = "dosei_proto"
version = { workspace = true }
edition = { workspace = true }

[lib]
path = "src/lib.rs"

[dependencies]
prost = { workspace = true }

[build-dependencies]
prost-build = { workspace = true }
