[package]
name = "proxy"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
axum = "0.7.2"
hyper = { version = "1.0.0", features = ["full"] }
hyper-util = { version = "0.1.1", features = ["client-legacy"] }
tokio = { version = "1", features = ["full"] }
