CREATE TABLE node (
  id UUID PRIMARY KEY,
  ip TEXT NOT NULL UNIQUE,
  port SMALLINT NOT NULL DEFAULT 8080,
  is_main BOOLEAN NOT NULL DEFAULT false,
  last_heartbeat_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
