[package]
name = "dosei"
version = { workspace = true }
edition = { workspace = true }

[[bin]]
path = "src/main.rs"
name = "dosei"

[dependencies]
dosei_proto = { workspace = true }

clap = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
serde_json = { workspace = true }
serde = { workspace = true, features = ["derive"] }
prost = { workspace = true }
