name: dctl-ci

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    name: 'build ${{ matrix.target }}'
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
#          TODO: Implement
#          - os: ubuntu-latest
#            target: aarch64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dsherret/rust-toolchain-file@v1

      - name: Install ${{ matrix.target }}
        run: rustup target add ${{ matrix.target }}

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true

      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Release
        run: cargo build --package dctl --target ${{ matrix.target }} --release

      - name: Zip (Linux/MacOS)
        if: matrix.os != 'windows-latest'
        run: zip -j dctl-${{ matrix.target }}.zip target/${{ matrix.target }}/release/dctl

      - name: Zip (Windows)
        if: matrix.os == 'windows-latest'
        run: Compress-Archive -CompressionLevel Optimal -Force -Path target/${{ matrix.target }}/release/dctl.exe -DestinationPath dctl-${{ matrix.target }}.zip

      - name: Upload Zip
        uses: actions/upload-artifact@v3
        with:
          name: dctl
          path: dctl-${{ matrix.target }}.zip

  release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dctl
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dctl-x86_64-unknown-linux-gnu.zip
            dctl-x86_64-apple-darwin.zip
            dctl-aarch64-apple-darwin.zip
            dctl-x86_64-pc-windows-msvc.zip
      - name: Print files sha256
        run: |
          shasum -a 256 \
          dctl-x86_64-unknown-linux-gnu.zip \
          dctl-x86_64-apple-darwin.zip \
          dctl-aarch64-apple-darwin.zip \
          dctl-x86_64-pc-windows-msvc.zip
